"""mensagem da migração

Revision ID: 016e896fb91a
Revises: 3e6f04938214
Create Date: 2025-12-04 19:09:25.266761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016e896fb91a'
down_revision = '3e6f04938214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roupa_create',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roupa_create')
    # ### end Alembic commands ###
